name: Ejecutar Bot ImportoK

on:
  schedule:
    # Corre a las 14:00 UTC (11:00 AM Argentina) y 19:00 UTC (4:00 PM Argentina) de lunes a viernes
    - cron: '0 14,19 * * 1-5'
  workflow_dispatch: # Esto nos permite probar el bot manualmente desde la web cuando queramos

jobs:
  actualizar-datos:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Le da permiso a GitHub para guardar el archivo modificado

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar librerias necesarias
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Ejecutar el Bot
      run: python bot.py

    - name: Guardar cambios en GitHub de forma automatica
      run: |
        git config --global user.name "importok-bot[bot]"
        git config --global user.email "importok-bot[bot]@users.noreply.github.com"
        git add datos.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Actualizacion automatica de tasas e impuestos" && git push)